class Login_Page_Objects:
    USER_INPUT_FIELD = "input[name='username']"
    PWD_INPUT_FIELD = "input[name='password']"
    LOGIN_BUTTON = "button[type='submit']"
    LOGIN_ERROR_MESSAGE = ".oxd-alert-content-text"
    LOGO = ".orangehrm-login-branding"
    BRANDING_IMAGE = "img[alt='company-branding']"
    LOGIN_TITLE = ".orangehrm-login-title"
    CREDENTIALS_INFO = ".orangehrm-demo-credentials"
    FORGOT_PWD_LINK = ".orangehrm-login-forgot"
    COMPANY_LINK = ".orangehrm-login-footer a"
    FOOTER = ".orangehrm-login-footer"
    USERNAME_PWD_GROUP = ".oxd-input-group"
    USERNAME_PWD_REQUIRED = ".oxd-input-field-error-message"
    DASHBOARD_HEADER = ".oxd-topbar-header-breadcrumb"
    CREDENTIALS_INFO_2 = "xpath=//text()[contains(.,'Username')]"
    FORGOT_PWD_PAGE_LOCATOR = "h6"
    TOPBAR_LOCATOR = ".oxd-topbar-header-breadcrumb"
    ALERT_CONTENT_LOCATOR = ".oxd-alert-content-text"